export const PLAYER_JOINED = "player-joined"
export const PLAYER_LEAVED = "player-leaved"
export const PLAYER_SET = "player-set"
export const GAME_START = "game:start"
export const GAME_STOP = "game:stop"
export const GAME_DRAW = "game:draw"
export const GAME_START_DRAW = "game:start-draw"
export const GAME_NEXT_ROUND = "game:next-round"
export const GAME_SET_ANSWER = "game:set-answer"
export const GAME_SEND_ANSWER = "game:send-answer"
export const GAME_TIMER = 60

export const pictionaryWordsArr = [
  "Back seat",
  "Highchair",
  "Rock band",
  "Birthday",
  "Hockey",
  "Sasquatch",
  "Black hole",
  "Hotel",
  "Scrambled eggs",
  "Blizzard",
  "Jump rope",
  "Seat belt",
  "Burrito",
  "Koala",
  "Skip",
  "Captain",
  "Leprechaun",
  "Solar eclipse",
  "Chandelier",
  "Light",
  "Space",
  "Crib",
  "Mask",
  "Stethoscope",
  "Cruise ship",
  "Mechanic",
  "Stork",
  "Dance",
  "Mom",
  "Sunburn",
  "Deodorant",
  "Mr Potato Head",
  "Thread",
  "Facebook",
  "Pantyhose",
  "Tourist",
  "Flat",
  "Paper plate",
  "United States",
  "Frame",
  "Photo",
  "WiFi",
  "Full moon",
  "Pilgram",
  "Zombie",
  "Game",
  "Pirate",
  "Back seat",
  "Highchair",
  "Rock band",
  "Birthday",
  "Hockey",
  "Sasquatch",
  "Black hole",
  "Hotel",
  "Scrambled eggs",
  "Blizzard",
  "Jump rope",
  "Seat belt",
  "Burrito",
  "Koala",
  "Skip",
  "Captain",
  "Leprechaun",
  "Solar eclipse",
  "Chandelier",
  "Light",
  "Space",
  "Crib",
  "Mask",
  "Stethoscope",
  "Cruise ship",
  "Mechanic",
  "Stork",
  "Dance",
  "Mom",
  "Sunburn",
  "Deodorant",
  "Mr Potato Head",
  "Thread",
  "Facebook",
  "Pantyhose",
  "Tourist",
  "Flat",
  "Paper plate",
  "United States",
  "Frame",
  "Photo",
  "WiFi",
  "Full moon",
  "Pilgram",
  "Zombie",
  "Game",
  "Pirate",
  "Back seat",
  "Highchair",
  "Rock band",
  "Birthday",
  "Hockey",
  "Sasquatch",
  "Black hole",
  "Hotel",
  "Scrambled eggs",
  "Blizzard",
  "Jump rope",
  "Seat belt",
  "Burrito",
  "Koala",
  "Skip",
  "Captain",
  "Leprechaun",
  "Solar eclipse",
  "Chandelier",
  "Light",
  "Space",
  "Crib",
  "Mask",
  "Stethoscope",
  "Cruise ship",
  "Mechanic",
  "Stork",
  "Dance",
  "Mom",
  "Sunburn",
  "Deodorant",
  "Mr Potato Head",
  "Thread",
  "Facebook",
  "Pantyhose",
  "Tourist",
  "Flat",
  "Paper plate",
  "United States",
  "Frame",
  "Photo",
  "WiFi",
  "Full moon",
  "Pilgram",
  "Zombie",
  "Game",
  "Pirate",
  "Back seat",
  "Highchair",
  "Rock band",
  "Birthday",
  "Hockey",
  "Sasquatch",
  "Black hole",
  "Hotel",
  "Scrambled eggs",
  "Blizzard",
  "Jump rope",
  "Seat belt",
  "Burrito",
  "Koala",
  "Skip",
  "Captain",
  "Leprechaun",
  "Solar eclipse",
  "Chandelier",
  "Light",
  "Space",
  "Crib",
  "Mask",
  "Stethoscope",
  "Cruise ship",
  "Mechanic",
  "Stork",
  "Dance",
  "Mom",
  "Sunburn",
  "Deodorant",
  "Mr Potato Head",
  "Thread",
  "Facebook",
  "Pantyhose",
  "Tourist",
  "Flat",
  "Paper plate",
  "United States",
  "Frame",
  "Photo",
  "WiFi",
  "Full moon",
  "Pilgram",
  "Zombie",
  "Game",
  "Pirate",
  "Highchair",
  "Rock band",
  "Birthday",
  "Hockey",
  "Sasquatch",
  "Black hole",
  "Hotel",
  "Scrambled eggs",
  "Blizzard",
  "Jump rope",
  "Seat belt",
  "Burrito",
  "Koala",
  "Skip",
  "Captain",
  "Leprechaun",
  "Solar eclipse",
  "Chandelier",
  "Light",
  "Space",
  "Crib",
  "Mask",
  "Stethoscope",
  "Cruise ship",
  "Mechanic",
  "Stork",
  "Dance",
  "Mom",
  "Sunburn",
  "Deodorant",
  "Mr Potato Head",
  "Thread",
  "Facebook",
  "Pantyhose",
  "Tourist",
  "Flat",
  "Paper plate",
  "United States",
  "Frame",
  "Photo",
  "WiFi",
  "Full moon",
  "Pilgram",
  "Zombie",
  "Game Pirate"
]
